[package]
name = "fastbuf"
version = "0.26.0"
edition = "2021"
author = "Bruce0203 <brucefreedy@gmail.com>"
description = "fast byte buffer with no async support"
repository = "https://github.com/Bruce0203/fastbuf"
license = "MIT"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dev-dependencies]
arrayvec = "0.7.4"
divan = "0.1.14"
fast_collections = "0.64.0"
rand = "0.8.5"

[features]
default = ["std"]
embedded-io = ["dep:embedded-io"]
std = []

# [[bench]]
# name = "sandbox"
# harness = false

[[bench]]
name = "compare_write_vs_try_write"
harness = false

[profile.bench]
lto = true

[dependencies]
embedded-io = { version = "0.6.1", optional = true }
