[package]
name = "fastbuf"
version = "0.18.0"
edition = "2021"
author = "Bruce0203 <brucefreedy@gmail.com>"
description = "fast byte buffer with no async support"
repository = "https://github.com/Bruce0203/fastbuf"
license = "MIT"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dev-dependencies]
arrayvec = "0.7.4"
divan = "0.1.14"
fast_collections = "0.64.0"
rand = "0.8.5"

[features]
default = ["std"]
std = []

[[bench]]
name = "benchmark"
harness = false

[profile.bench]
lto = true

[dependencies]
varuint = "0.7.1"

